.PHONY: install

SECTION: NetPing modules
CATEGORY: Base
TITLE: OWRT-WEB-netping-schema
PKG_NAME: owrt-web-netping-schema
PKG_VERSION: 0.1
PKG_RELEASE: 1

install:
	cp -r ./root/etc/uci-defaults /etc
	cp -r ./htdocs/luci-static /www
	cp -r ./htdocs/cgi-bin /www
	cp -r ./luasrc/view /usr/lib/lua/luci
	chmod 744 /etc/uci-defaults/30_luci-theme-netping
	chmod 755 /www/cgi-bin/over_ref.cgi
	/etc/uci-defaults/30_luci-theme-netping
	reboot
