#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
    uci get luci.themes.netping >/dev/null 2>&1 || \
    uci batch <<-EOF
	set luci.themes.netping=/luci-static/netping
	set luci.main.mediaurlbase=/luci-static/netping
	commit luci
    EOF
fi

sed -i 's/admin_status/netping_status/' /usr/share/luci/menu.d/luci-mod-status.json
exit 0