#!/bin/sh

	uci get luci.themes.netping >/dev/null 
	uci batch <<-EOF
	set luci.themes.netping=/luci-static/netping
	set luci.main.mediaurlbase=/luci-static/netping
	commit luci
	EOF

rm -f /www/luci-static/resources/view/status/include/10_system.js
rm -f /www/luci-static/resources/view/status/include/30_network.js
rm -f /www/luci-static/resources/view/status/include/40_dhcp.js
rm -f /www/luci-static/resources/view/status/include/50_dsl.js
rm -f /www/luci-static/resources/view/status/include/60_wifi.js
rm -f  /usr/lib/lua/luci/controller/opkg.lua
rm -f  /usr/lib/lua/luci/controller/admin/network.lua
rm -f  /usr/lib/lua/luci/controller/firewall.lua
mv -f /www/luci-static/netping/*.json /usr/share/luci/menu.d/

exit 0
